### ISSUE TITLE
'지제' -> '평택지제' 반영이 필요합니다.

### ISSUE THREAD

**Issue by yunikim77** [ryanking13/SRT#220]
수고많으십니다.
search_train 할때 역명을 '평택지제'로 하니 not exists 예외가 발생하네요..
기존 이름인 '지제'로는 정상 동작 하구요.
변경된 역명에 대한 반영이 필요할것 같아요.

**Comment by ryanking13** [comment]
안녕하세요, 알려주셔서 감사합니다. 역명을 수정하는 PR을 보내실 생각이 있으실까요?

**Comment by yunikim77** [comment]
안녕하세요.
PR 드렸습니다.
수고하세요~
