### ISSUE TITLE
지금 정상동작 안하는건가요?

### ISSUE THREAD

**Issue by cys4585** [ryanking13/SRT#235]
기존에 동작하던 소스가 어제부터 동작이 안되네요.
`SRT()` 에서 에러가 발생합니다. 혹시 소스가 아니라 해당 계정이 문제일까요?
![image](https://github.com/ryanking13/SRT/assets/77481524/d7ba3f95-1765-4e8c-9243-ca8ca388e99d)

**Comment by ryanking13** [comment]
@cys4585 SRT 서버가 불안정하거나, 혹은 현재 계신 곳의 인터넷 연결이 불안정한 것으로 보이는데요. 제 로컬 환경에서는 잘 작동해서 다른 인터넷 환경에서 시험을 해보시겠어요?

**Comment by cys4585** [comment]
네트워크의 문제였던 것 같습니다. 다른 인터넷 환경에서 정상동작하는 것을 확인했습니다.
답변 감사합니다. :)
