### ISSUE TITLE
The `is_login` status check seems unnecessary for the `search_train` function.

### ISSUE THREAD

**Issue by Nitro1231** [ryanking13/SRT#237]
우선 라이브러리 개발 노고에 감사드립니다. 덕분에 잘 사용하고 있습니다! (_ _)

https://github.com/ryanking13/SRT/blob/758ba0232326539c365dd6f97d6bd6839b52c785/SRT/srt.py#L181-L182

`srt.py` 스크립트의 `search_train` 함수의 기능을 고려할때, 181~182번째 줄에 있는 `is_login` 확인문이 꼭 필요해 보이지 않습니다. 더 나아가 유저의 로그인 정보 없이 열차 정보를 가져오는 기능이 있다면 그냥 열차 정보만 필요할때 유용할듯 합니다. 혹시 로그인 확인문을 넣으신 이유가 있으실까요?

**Comment by ryanking13** [comment]
안녕하세요. 그렇네요, 검색은 굳이 로그인 체크가 필요하지 않을 것 같습니다. 관련하여 수정하는 PR을 올리는 데에 관심이 있으실까요?
