### ISSUE TITLE
열차 정보 출력시 열차 번호 추가 PR을 드렸습니다.

### ISSUE THREAD

**Issue by yunikim77** [ryanking13/SRT#246]
수고많으십니다.
SRT를 이용하다보니 동일 날짜, 동일 시간에 2대의 열차가 운영되는 경우도 있었습니다.
<img width="708" alt="스크린샷 2023-09-02 오후 6 44 35" src="https://github.com/ryanking13/SRT/assets/35764837/ed33255b-1a0a-41cd-b972-46d22b345827">

열차번호는 다르지만, 날짜, 시간이 같아 열차정보 출력시 구분이 안됩니다.
그래서  SRTrain 인스턴스 dump 시에 열차번호도 함께 출력될 수 있도록 수정하여 PR 드렸습니다.
접두에 [SRT] 만 출력되던 것을 [SRT 322] 와 같이 열차 번호도 함께 출력되도록 하였습니다.
검토 한번 부탁드립니다.

**Comment by ryanking13** [comment]
감사합니다~ 번호로 봐서는 중련편성을 저렇게 나타내는 것처럼 보이는데 신기하군요.

**Comment by ryanking13** [comment]
Closing as resolved by #245
