### ISSUE TITLE
time_limit (str, optional) – 출발 시각 조회 한도 (hhmmss) 설명

### ISSUE THREAD

**Issue by page-a** [ryanking13/SRT#262]
좋은 기능 감사합니다. 한 가지 질문이 있어요
search train에서 한도를 설정할 수 있던데요
time_limit (str, optional) – 출발 시각 조회 한도 (hhmmss)
를 적용하는 것이 무슨 의미일까요?
10시~ 11시(11시포함) 사이 예약하려고 할 때
time에 100000넣고 time_limit에 110001 이렇게 하면 될까요?

**Comment by ryanking13** [comment]
출발 시각 기준으로 `time_limit` 이전인 차량만 조회합니다.

> time에 100000넣고 time_limit에 110001 이렇게 하면 될까요?

`time_limit` 을 `110000`으로 넣으시면 됩니다. inclusive 입니다.

https://github.com/ryanking13/SRT/blob/92383b3a68e353f3d7f04fac82a09700e33b20cc/SRT/srt.py#L248

**Comment by page-a** [comment]
답변 감사합니다 
행복하세요~
