### ISSUE TITLE
JS, TS 버전 만들어봤습니다!

### ISSUE THREAD

**Issue by 0xDaizz** [ryanking13/SRT#263]
https://github.com/0xDaizz/SRT-ts

취미삼아 코딩하다가 ryanking님 소스 발견하고,
파이썬 버전은 많은데 JS 쪽이 빈약한 것 같아 코딩 공부도 해볼 겸 
GPT 도움받아 타입스크립트 버전으로 리모델링 해보았습니다.

좋은 라이브러리 정말 감사인사 드립니다 ㅎㅎㅎ!!

**Comment by ryanking13** [comment]
멋지네요, 공유 감사합니다 :)
