### ISSUE TITLE
reserve_standby에서 passengers가 [Adult(), Adult(), Child()] 일때

### ISSUE THREAD

**Issue by j-yschoi** [ryanking13/SRT#266]
안녕하세요?
유용한 패키지 잘 사용하고 있습니다.

보통 1인 예약하여 passengers를 [Adult()]로 호출하여 문제없이 잘 사용하였으나, 어른2아이1의 구성으로 passengers로 [Adult(), Adult(), Child()]으로 reserve_standby를 호출하게 되면 '장애의정도가심한장애인 할인' 표가 2장 예약됩니다.
참고로 reserve는 정상적으로 3석 예약이 됩니다.

srt.reserve_standby(train, passengers=[Adult(), Adult(), Child()], special_seat=SeatType.GENERAL_ONLY, mblPhone='010-xxxx-xxxx') # 이상 동작
srt.reserve(train, passengers=[Adult(), Adult(), Child()], special_seat=SeatType.GENERAL_ONLY, window_seat=True) # 정상 동작
srt.reserve_standby(train, passengers=[Adult()], special_seat=SeatType.GENERAL_ONLY, mblPhone='010-xxxx-xxxx') # 정상 동작

그럼 확인 부탁드립니다.

**Comment by ryanking13** [comment]
감사합니다 수정하였습니다.
