### ISSUE TITLE
srt api 예약시 오류

### ISSUE THREAD

**Issue by flixzf** [ryanking13/SRT#271]
비컴공이 혼자서 기능들 추가하면서 재미있게 해보고 있습니다. 감사합니다.

연동하여 시험삼아 예매 해봤는데 예약시 " 정상적인 경로로 접근 부탁드립니다" 발생하는데 해결방안이 있을까요?

여러 가지 검색루트로 검색해보았는데 SRT쪽에서 api 사용을 못하게 막았다는 결론을 냈는데 그게 맞을까요?

**Comment by Monsteel** [comment]
#272 에서 해당문제에 대한 해결을 처리중입니다.

**Comment by ryanking13** [comment]
Resolved by https://github.com/ryanking13/SRT/pull/272
