### ISSUE TITLE
SRT.errors.SRTResponseError: 정상적인 경로로 접근 부탁드립니다.

### ISSUE THREAD

**Issue by ksy980418** [ryanking13/SRT#274]
search_train을 호출할 경우 아래의 error가 발생하네요.
SRT 측에서 api를 바꾼 걸까요?

SRT.errors.SRTResponseError: 정상적인 경로로 접근 부탁드립니다.

**Comment by Monsteel** [comment]
#271 과 동일한 이슈이며, #272 PR에서 수정 작업중입니다.

**Comment by ryanking13** [comment]
Resolved by #272
