### ISSUE TITLE
search_train 함수 호출시 SRTNetFunnelError 예외 발생.

### ISSUE THREAD

**Issue by yunikim77** [ryanking13/SRT#279]
매진된 열차를 선택하여 search_train 함수를 호출하는 상황이었는데
아래와 같은 예외가 발생하며 정상적으로 결과를 얻지 못하고 있습니다.
 
<img width="891" alt="스크린샷 2024-12-23 21 41 17" src="https://github.com/user-attachments/assets/b3a2faa5-9022-4d3e-ad69-f671425ad4e7" />

SRT.search_train 메소드내의  _search_train(..) 호출하는 코드에서 use_netfunnel_cache 를
기본값 True에서 False로 변경해 보니 위의 예외가 발생하지 않고 정상적으로 진행은 되는데,
이것이 올바른 해결책인지는 모르겠습니다.

**Comment by ryanking13** [comment]
감사합니다. #278에서 해당 이슈 처리하고 있었으니, v2.6.2로 업데이트하고 확인해주시면 감사하겠습니다.
