### ISSUE TITLE
NetFunnel permission deny 예외 발생.

### ISSUE THREAD

**Issue by yunikim77** [ryanking13/SRT#282]
안녕하세요.

아래와 같이 대기자가 있는 경우에 계속 시도시 대기자가 줄어들다가 결국 permission deny 가 발생되고 있습니다.
대기자 발생의 경우가 아닐때는 문제가 발생되지 않는것 같습니다.

<img width="890" alt="스크린샷 2024-12-27 10 20 03" src="https://github.com/user-attachments/assets/7830ef87-b21c-40d5-a112-e6baf1aaec07" />

**Comment by ryanking13** [comment]
버전 업데이트를 해보시겠어요? NetFunnel 관련 버그를 수정한 v2.6.2 를 며칠 전 릴리즈했는데, 로그로 봐서는 구버전을 사용하고 있으신듯 합니다

**Comment by ryanking13** [comment]
Edit: 코멘트가 잘못되어 수정합니다.

시간이 될 때 살펴볼게요 감사합니다

**Comment by ryanking13** [comment]
원인으로 추정되는 부분을 수정했습니다. 라이브러리 업데이트 후에도 재발하면 알려주세요.

**Comment by yunikim77** [comment]
네. 빠른 확인 감사합니다.

**Comment by yunikim77** [comment]
일단, 금일 릴리즈된 2.6.3을 짧게 확인한 내용입니다.
같은 조건에서 바로 문제가 발생하는 것은 아니며, 어느정도 개선은 되었습니다,
하지만, 이상태에서 계속적으로 search_train 시도하다보면 어느순간 다시 문제가 나타나며,
한번 예외 발생하면 이후는 지속적으로 동일 예외 발생합니다.
추가적으로 예외발생 조건이 있는지 확인되면 다시 comment 하겠습니다.

**Comment by yunikim77** [comment]
안녕하세요.
다른 예외가 나오기는 하는데,,,
permmission deny는 더이상 나오지 않는것 같으니 본 이슈는 close 하면 될것 같습니다.

**Comment by hyungilkim** [comment]
> Edit: 재확인시 추가 확인된 내용이 있어 수정하였습니다.
> 
> 일단, 금일 릴리즈된 2.6.3을 짧게 확인한 내용입니다. 같은 조건에서 바로 문제가 발생하는 것은 아니며, permission deny 예외는 개선된 것으로 보입니다. 하지만, 이상태에서 계속적으로 search_train 시도하다보면 이번에는 "Wrong Server id" 예외가 발생하며, 한번 예외 발생시 이후 지속적으로 동일 예외 발생합니다.
> 
> 다른 확인사항 있으면 comment 하겠습니다.

저도 Wrong Server id 예외가 계속 발생하네요..

**Comment by ryanking13** [comment]
@hyungilkim 

감사합니다. 에러 로그를 좀 더 자세하게 올려주시면 확인에 도움이 될 것 같습니다.
