### ISSUE TITLE
srt.reserve 시에 "로그인 후 사용하십시요." response

### ISSUE THREAD

**Issue by ChangWanHong** [ryanking13/SRT#67]
srt.login() 성공 후에, srt.search_train()으로 받은 train으로 srt.reserve() 시도시에 
```로그인 후 사용하십시요.```
라고 response가 나옵니다.

현재 HEAD는 ab108278399c400028998078091077aae11c2a01 입니다.

**Comment by ryanking13** [comment]
저는 reproduce가 안 되는데, 사용하신 코드와 실행 환경을 알려주실 수 있을까요?

**Comment by ryanking13** [comment]
계속 문제가 발생하시면 이슈를 reopen 해주세요!
